%% Introduction
%% Welcome
% Welcome to the Zaber Device Control Toolbox. With this you can easily
% control <https://www.zaber.com/ Zaber Technologies> motion stages from
% within MATLAB.
%% Features
% * Control Zaber devices using either the Zaber ASCII or Zaber Binary 
%   communication protocols, at any supported baud rate.
% * Simplified interface for common motion commands and controller I/O
%   ports. 
% * Communication helpers are exposed to enable easier access to advanced 
%   device features not covered by the simplified interface.
% * Optional autodetection of protocol and devices.
% * Has no dependencies on non-core toolboxes or third-party toolboxes.
%
% The toolbox provides two layers of access, which can be mixed as needed:
%
% <html>
% <ol>
% <li>Protocol layer.
%     <ul>
%     <li> Provides assistance with formatting and parsing messages in the
%          Zaber Binary and Zaber ASCII protocols.</li>
%     <li> Provides the ability to detect which protocol is in use by the
%          first device on your daisy chain.</li>
%     <li> Provides the ability to detect which devices are present on your
%          port, so you can use layer 2:</li>
%     </ul>
% <li> Device layer.
%     <ul>
%     <li> Provides class interfaces to your devices.</li>
%     <li> Determine the properties of the devices (name, type etc).</li>
%     <li> Use protocol-agnostic methods to perform common operations:
%         <ul>
%         <li>Determine the name and motion type of a device.</li>
%         <li>Get the movement range.</li>
%         <li>Move to an absolute position.</li>
%         <li>Move by a relative amount.</li>
%         <li>Move at a specified velocity.</li>
%         <li>Move to an indexed position.</li>
%         <li>Move to the home position.</li>
%         <li>Get the current position.</li>
%         <li>Wait for a move to finish.</li>
%         <li>Stop any movement in progress.</li>
%         <li>Determine what I/O ports are present.</li>
%         <li>Read from analog and digital input ports and write to digital 
%             output ports.</li>
%         </ul>
%     </ul>
% </ol>
% </html>
%    
% The toolbox also provides conversions between native device units of
% measure and meters, degrees and their derivatives for most devices.
%
% *Not Implemented*
%
% The following features are not present in this toolbox.
%
% * This toolbox is not thread safe. 
% * Device replies are not automatically correlated with commands sent. To 
%   avoid confusion, especially with the Binary protocol, we recommend that 
%   you avoid overlapping commands.
% ** This means that messages spontaneously generated by devices, such as 
%    binary move tracking notifications and ASCII alerts, will interfere
%    with communication. We recommend disabling Manual Move Tracking
%    responses to limit the amount of interference. Contact Zaber 
%    technical support for assistance with this at contact@zaber.com.
% * The toolbox does not detect the use of device commands that may 
%   invalidate the state of its data structures. 
% ** If you change a device's communication protocol, baud rate, address, 
%    peripheral ID, resolution or any other property that may affect the 
%    state of your MATLAB data structures, you are responsible for 
%    reconstructing them.
% * Unit conversions are not provided for devices that have a mechanism that 
%   is not purely linear or rotary, such as the OMG product line.
% * The toolbox currently has no awareness of lockstep and virtual axis 
%   modes. Devices may not behave as expected if used with this toolbox 
%   while in one of these modes.

%% Requirements
% Zaber motion devices connect to a PC via an RS-232 serial connection.
% Depending on the connectors present on your devices and your computer,
% this might be accomplished with a serial cable, a USB cable or a
% USB-to-serial adaptor cable. Consult the product manual for your device
% and the Zaber <https://www.zaber.com/documents/Getting-started-guide.pdf
% Getting Started Guide (PDF)>.
%
% You will need either a Windows or a Linux operating system with MATLAB
% and the appropriate drivers for your serial hardware. You will need to
% know what name your operating system assigns to the serial port your
% Zaber devices are connected to. Under Windows this is typically something
% like 'COM1'. Under Linux it is often similar to '/dev/ttyS1' or
% '/dev/ttyUSB0'.
%
% This toolbox has no dependencies outside of the core MATLAB installation.
% You do not need any additional MathWorks or third-party toolboxes.
%
% Although you can use this toolbox to configure your Zaber devices (that
% is, assign them addresses, change their communication settings, and
% change the settings that control their behavior), we recommend using
% <https://www.zaber.com/wiki/Software/Zaber_Console Zaber Console> to
% perform the initial configuration. It provides a faster and easier way to
% identify and configure multiple devices.

%% BETA Software
%
% This toolbox is in early development and should be considered unstable 
% until this notice is removed.
%
% The implication of this is that you should expect to see breaking changes 
% in new versions until it stabilizes. Check the change log before deciding 
% whether or not to adopt a new version.

